language: cpp
compiler:
  - gcc
  - clang
script: make 
env:
  global:
	  - secure: "S9W0kw0CCEaDO0Eu9kFrguhEkeuyP7Vm5GZCvCLCrB2DtDa68/0VW5WuZTzoLqIDMOpHEzHhXDgcFLm65KGwnRvjkRlr6Lgp5kD4Y6ZmZf8pLHR7XriRYkWjc/brJCbBjj1570Qao2zDZzhJHDiiAm0ybJHuUqcG0USGcqGqZU0="
after_success:
	- ## the following automatically builds the doxygen 
	- ## documentation and pushes it to the gh_pages branch 
	- 
	- # First, set up credentials using the environment variables 
	- # GIT_NAME, GIT_EMAIL and GH_TOKEN. These were passed
	- # encrypted to travis and should have been decrypted 
	- # using travis’ private key before this script was run.
	- git config user.name ${GIT_NAME}
	- git config user.email ${GIT_EMAIL}
	- git config credential.helper "store --file=.git/credentials"
	- echo https://${GH_TOKEN}:@github.com >> .git/credentials
  -
	- # now we make the directory for the docs and cd into it
	- mkdir developmentDocs
	- cd developmentDocs/
  -
	- # clone the whole repo again, but switch to gh_pages branch
	- git clone https://github.com/pjuren/TinyTest .
	- git checkout gh-pages
  -
	- # go back up and build the documentation, pointing it towards
	- # that dir we just made
	- cd ../
	- make developmentDocs
  -
	- # cd into the docs dir and commit and push the new docs. 
	- cd developmentDocs
	- git add --all .
	- git commit -m "Auto-updating Doxygen developer documentation"
	- git push origin gh-pages
